import { Inter } from "next/font/google";
import "../styles/main.scss";
import Providers from "@/context/Providers";
import { ChatContextProvider } from "@/context/ChatContex";
import { AuthContextProvider } from "@/context/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Green Harvest ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <AuthContextProvider>
          <ChatContextProvider>
            <Providers>{children}</Providers>
          </ChatContextProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
